# Generated by Django 5.0.4 on 2024-04-21 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fridge_ingredients",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meals.ingredient",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UsersList",
        ),
    ]
