FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

WORKDIR /app

COPY requirements.txt ./
RUN pip install --user -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "fridge/manage.py", "runserver", "0.0.0.0:8000"]

